/** Re-exports the target-neutral analysis surface used by LSP providers. */
export {
  Assembler,
  WorkspaceIndex,
  OverlayFileProvider,
  findInstruction,
  findDirectiveEntry,
  findDirectiveInCatalog,
  buildCompletionEntries,
  renderInstructionDocs,
  renderDirectiveDocs,
  renderExpressionFunctionDocs,
  getInstructionCatalog,
  positionInRange,
  locationRange,
  referenceAt,
  symbolAt,
  resolveDefinition,
  findReferences,
} from "@uttori/asm-core";
