    db $0C
    dw be(..ch8), be(..ch7), be(..ch6), be(..ch5), be(..ch4), be(..ch3), be(..ch2), be(..ch1)

..ch8:
    %end_track()

..ch7:
    %end_track()

..ch6:
    %end_track()

..ch5:
    %end_track()

..ch4:
    %end_track()

..ch3:
    %tempo($01C7)
    %duration($DC)
    %note($00, 6)
    %octave($02)
    %instrument($00)
    %release($1F)
    %volume($5A)
    %toggle_2_octaves_up()
    %note($0F, 1)
    %portamento_time($7F)
    %volume($7F)
    %toggle_portamento()
    %toggle_2_octaves_up()
    %note($13, 1)
    %note($0F, 1)
    %note($0A, 1)
    %note($03, 1)
    %octave($01)
    %toggle_portamento()
    %note($0A, 1)
    %note($00, 2)
    %octave($00)
    %instrument($01)
    %release($18)
    %portamento_time($50)
    %toggle_portamento()
    %note($1D, 2)
    %toggle_2_octaves_up()
    %note($0A, 2)
    %toggle_portamento()
    %note($08, 2)
    %volume($1E)
    %toggle_portamento()
    %note($07, 2)
    %note($0C, 2)
    %duration($1E)
    %release($12)
    %toggle_portamento()
    %note($0C, 6)
    %portamento_time($00)
    %end_track()

..ch2:
    %end_track()

..ch1:
    %tempo($01C7)
    %duration($DC)
    %tuning($7F)
    %note($00, 6)
    %per_voice_transpose($FA)
    %octave($03)
    %instrument($05)
    %volume($5A)
    %toggle_2_octaves_up()
    %note($15, 1)
    %volume($7F)
    %note($01, 1)
    %toggle_2_octaves_up()
    %note($15, 1)
    %note($10, 1)
    %note($0A, 2)
    %note($00, 2)
    %instrument($00)
    %release($18)
    %portamento_time($50)
    %toggle_portamento()
    %note($02, 2)
    %note($07, 2)
    %toggle_portamento()
    %note($05, 2)
    %volume($1E)
    %toggle_portamento()
    %note($04, 2)
    %note($09, 2)
    %duration($1E)
    %release($12)
    %toggle_portamento()
    %note($09, 6)
    %end_track()
