import type { OperandResolver } from "../operand-resolver.js";
import type { NormalizedCommand } from "../ir/normalized-command.js";
import type { RomWriterService } from "../services/rom-writer-service.js";
import type { StructEngine } from "../services/struct-engine.js";
import type { SymbolScopeService } from "../services/symbol-scope-service.js";
import type { AssemblerServices } from "../assembler-internals.js";
import { ArchitectureRegistry } from "../architecture-registry.js";
import { SpcblockData } from "../assembler.js";
import { ExpressionNode } from "../ir/expression-node.js";
import type { AssemblyFileProvider } from "../file-provider.js";

export interface AssemblySession {
  recordCurrentAddress(): void;
  setWritePosition(address: number): void;
  evaluateRangeExpression(expression: string | ExpressionNode): number;
  readFile(filename: string): Uint8Array | string;
  architectureRegistry: ArchitectureRegistry;
  arch: string;
  fileProvider: AssemblyFileProvider;
  services: AssemblerServices;
  defines: Map<string, string>;
  namespaceStack: string[];
  namespaceNestingPath: string[];
  namespaceNestingEnabled: boolean;
  currentNamespace: string;
  tableStack: Map<string, number>[];
  characterMappings: Map<string, number>;
  currentTable: string | null;
  currentFile: string;
  includedFiles: Map<string, { included: boolean; guarded: boolean }>;
  targetRom: Uint8Array;
  romdata: number[] | Uint8Array;
  defaultFreespaceByte: number;
  activeFreespaceStartPc: number | null;
  activeFreespaceContentStartPc: number | null;
  fillbyte: number[];
  padbyte: number[];
  padUnit: number;
  currentTargetAddress: number;
  currentTargetBaseAddress: number;
  currentTargetStartAddress: number;
  currentTargetBaseStartAddress: number;
  mapper: string;
  checksumFixEnabled: boolean;
  sa1banks: number[];
  inSpcblock: boolean;
  spcInlineCompatMode: boolean;
  spcblockData: SpcblockData | null;
  readFunctionsEnabled: boolean;
  bankCrossCheckMode: "off" | "full" | "half";
  optimizeDirectPage: boolean;
  operandResolver: OperandResolver;
  romWriter: RomWriterService;
  structEngine: StructEngine;
  symbolScope: SymbolScopeService;
  pushBaseStack: number[];
  resolvedefines(input: string): string;
  assemblefile(filename: string, isMacro: boolean): void;
  expandRom(size: number, fillbyte: number): void;
  handleInclude(kind: string, filename: string, once: boolean): void;
  handleNamespace(args: string[]): void;
  handlePushNamespace(): void;
  handlePullNamespace(): void;
  handlePushPC(): void;
  handlePullPC(): void;
  handleOrg(args: string[]): void;
  handleDataDirective(keyword: string, args: string[]): void;
  handleSpcblock(words: string[]): void;
  handleEndSpcblock(words: string[]): void;
  write1(value: number): void;
  write2(value: number): void;
  write3(value: number): void;
  write4(value: number): void;
}

export interface DirectiveContext {
  session: AssemblySession;
  operandResolver: OperandResolver;
}

export type DirectiveHandler = (ctx: DirectiveContext, words: string[], raw: string, command?: NormalizedCommand) => void;
